baseURL = "https://greenstegwriting.github.io/"
languageCode = "en-us"
title = "Greensteg"
theme = "onetwothree"
pygmentsCodeFences = true
pygmentsStyle = "autumn"

[permalinks]
    posts = "/:slug/"

[params]
    email = "greensteg@gmail.com"
    navigation = ["about.md"]
